apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: camoufox-dr
  namespace: camoufox
spec:
  host: camoufox.camoufox.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
   