apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - deployment.yaml
  - statefulset.yaml

helmCharts:
  - name: scrapy-job-chart
    namespace: default
    releaseName: scrapy-job-chart
    valuesFile: values.yaml