apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy-job-api
  namespace: jobs
spec:
  template:
    spec:
      containers:
        - name: scrapy-job-api
          image: alexshrugged92/scrapy-job-api
          env:
            - name: "USE_NFS_STORAGE"
              value: "true"