apiVersion: apps/v1
kind: Deployment
metadata:
  name: camoufox
  # namespace: camoufox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camoufox
  template:
    metadata:
      labels:
        app: camoufox
    spec:
      containers:
      - name: camoufox-server
        # image: alexshrugged92/camoufox-server
        image: alexshrugged92/camoufox-server
        ports:
        - containerPort: 59001
        # env:
        #   - name: ENABLE_VNC
        #     value: "true"

