apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-apps-dev-nfs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: argocd
          path: k8s/apps/overlays/dev-nfs/argocd
        - name: camoufox
          path: k8s/apps/overlays/dev-nfs/camoufox
        - name: database
          path: k8s/apps/overlays/dev-nfs/database
        - name: metallb-config
          path: k8s/apps/overlays/dev-nfs/metallb-config
        - name: mock-ws-backend
          path: k8s/apps/overlays/dev/mock-ws-backend
        - name: monitoring-servicemonitors
          path: k8s/monitoring/overlays/dev
        - name: nfs-storage
          path: k8s/storage/overlays/dev-nfs
        - name: prometheus-config
          path: k8s/apps/overlays/dev-nfs/prometheus
        - name: proxy
          path: k8s/apps/overlays/dev-nfs/proxy
        - name: redis
          path: k8s/apps/overlays/dev-nfs/redis
        - name: redis-commander
          path: k8s/apps/overlays/dev-nfs/redis-commander
        - name: scrapy-job-api
          path: k8s/apps/overlays/dev-nfs/scrapy-job-api
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alexneuman/scrapy-pipeline-cluster-infrastructure.git'
        targetRevision: test
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
