apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: mock-ws-backend
          path: k8s/apps/common/mock-ws-backend
          # namespace: dev
        - name: database
          path: k8s/apps/common/database
          namespace: dev
        - name: camoufox
          path: k8s/apps/common/camoufox
          # namespace: dev
        - name: proxy
          path: k8s/apps/common/proxy
          # namespace: dev
        - name: redis
          path: k8s/apps/base/redis
        - name: argocd
          path: k8s/apps/base/argocd
          # namespace: dev
        - name: redis-commander
          path: k8s/apps/common/redis-commander
          namespace: dev
        # - name: scrapy-job
        #   path: k8s/apps/common/scrapy-job
          # namespace: dev
        - name: metallb-config
          path: k8s/apps/common/metallb
          # namespace: metallb-system
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alexneuman/scrapy-pipeline-cluster-infrastructure.git'
        targetRevision: test
        path: '{{path}}'
        # directory:
        #   recurse: true
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

