apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: mock-ws-backend
          path: k8s/apps/overlays/dev/mock-ws-backend
          # namespace: dev
        # - name: argo-workflows
        #   path: k8s/apps/base/argoworkflows
          # namespace: metallb-system
        - name: scrapy-job-api
          path: k8s/apps/overlays/dev/scrapy-job-api
          # namespace: 
        - name: database
          path: k8s/apps/overlays/dev/database
          # namespace: dev
        - name: camoufox
          path: k8s/apps/overlays/dev/camoufox
          # namespace: dev
        - name: proxy
          path: k8s/apps/overlays/dev/proxy
          # namespace: dev
        - name: redis
          path: k8s/apps/overlays/dev/redis
        - name: argocd
          path: k8s/apps/overlays/dev/argocd
          # namespace: dev
        - name: redis-commander
          path: k8s/apps/overlays/dev/redis-commander
          # namespace: dev
        - name: metallb-config
          path: k8s/apps/overlays/dev/metallb-config
          # namespace: metallb-system
        - name: prometheus-config
          path: k8s/apps/overlays/dev/prometheus
        - name: monitoring-servicemonitors
          path: k8s/monitoring/overlays/dev
          
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alexneuman/scrapy-pipeline-cluster-infrastructure.git'
        targetRevision: test
        path: '{{path}}'
        # directory:
        #   recurse: true
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

