# pv-dummy.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: ""
#   persistentVolumeReclaimPolicy: Delete
#   volumeMode: Filesystem
#   hostPath:
#     path: /tmp/dummy-argo