apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-argo-workflows
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
