apiVersion: v1
kind: PersistentVolume
metadata:
  name: scrapy-cache-pv
  namespace: scrapy-job
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /home/wireshark-server/backup/scrapy-cache
    # server: 10.96.0.50
    server: 192.168.50.165