apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scrapy-job
  namespace: scrapy-job
  labels:
    app: scrapy-job
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scrapy-job
  template:
    metadata:
      labels:
        app: scrapy-job
    spec:
      containers:
        - name: scrapy-job
          image: scrapy-job
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: zone
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: scrapy-deployment
