apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-operated
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus.scrapeops.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-operated
            port:
              number: 80
  - host: prometheus.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-operated
            port:
              number: 80