server:
  auth: false
  insecure: true
  extraArgs: ["--auth-mode=server"]
  ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts: [
        "workflows.askaboutmydad.shop"
      ]
      paths:
        - /
      pathType: Prefix
      extraPaths: []