apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-charts
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
        - list:
            elements:
              - env: "dev"
        - git:
            repoURL: 'https://github.com/alexneuman/scrapy-pipeline-cluster-infrastructure.git'
            revision: test            # branch to track
            directories:
              - path: 'k8s/helm/values/{{env}}/*'   # wildcard matches all subfolders with Helm charts
  template:
    metadata:
      name: '{{path.basename}}' # Application name = folder name
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alexneuman/scrapy-pipeline-cluster-infrastructure.git'
        targetRevision: test
        path: 'k8s/helm/charts/{{path.basename}}'         # folder containing the chart
        helm:
          valueFiles:
            - "../../values/{{env}}/values.yaml"
            # - "../../values/{{env}}/{{path.basename}}/values.yaml"       # values file in each chart folder
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # deploy each chart to its own namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
