apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: "1.62.0"
    helm:
      releaseName: kiali-operator
      parameters:
        - name: cr.create
          value: "true"
        - name: cr.namespace
          value: "istio-system"
        - name: cr.spec.auth.strategy
          value: "anonymous"
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true