
resources:
  - ../../dev
  - pv.yaml

patches:
  # - path: pv.yaml
  #   target:
  #     kind: PersistentVolume
  #     name: pv
  - path: pvc-argo-jobs.yaml
    target:
      kind: PersistentVolumeClaim
      name: pvc-argo-workflows