CONCURRENCY_PER_SPIDER: "5"
REDIS_CACHE_ENABLED: true
REDIS_ENABLED: true
PLAYWRIGHT_ENABLED: true
PLAYWRIGHT_HEADLESS: true
SPIDER_IMAGE: "scrapy"
SPIDER_NAME: "apple_jobs"
SPIDER_REPLICAS: "1"
LOG_LEVEL: INFO
PLAYWRIGHT_MAX_CONTEXTS: 250
SPIDER_RETRIES: 4