apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: camoufox-scaler
  # namespace: camoufox
  labels:
    scaledobject.keda.sh/name: camoufox-scaler
spec:
  scaleTargetRef:
    name: camoufox     
    kind: StatefulSet  
    apiVersion: apps/v1
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: kubernetes-workload
      metadata:
        namespace: default
        podSelector: app=scrapy-job
        value: "1"
